### ISSUE TITLE
🏆 Awesome and epic initiative from gorgrud

### ISSUE THREAD

**Issue by gorgrud** [xpirit-training/github-fundamentals-liebherr#12]
```[tasklist]
### Tasks
- [ ] 🎸 A feature from gorgrud that rocks
- [ ] ⚡ Another epic feature from gorgrud
- [ ] 🔥 Hot feature from gorgrud
```
