### ISSUE TITLE
🏆 Awesome and epic initiative from loschee

### ISSUE THREAD

**Issue by loschee** [xpirit-training/github-fundamentals-liebherr#26]
```[tasklist]
### Tasks
- [ ] 🎸 A feature from loschee that rocks
- [ ] ⚡ Another epic feature from loschee
- [ ] 🔥 Hot feature from loschee
```
