### ISSUE TITLE
🏆 Awesome and epic initiative from wajonas

### ISSUE THREAD

**Issue by wajonas** [xpirit-training/github-fundamentals-liebherr#56]
```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
- [ ] 🎸 A feature from [wajonas] that rocks
- [ ] ⚡ Another epic feature from @wajonas 
- [ ] 🔥 Hot feature from @wajonas 

```
